// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJKnv2ned1lbER0sBM09S3QwD8IHWhx04',
    appId: '1:500945831833:web:fd4df5b45aa3bb3f2f3508',
    messagingSenderId: '500945831833',
    projectId: 'confess-272ce',
    authDomain: 'confess-272ce.firebaseapp.com',
    storageBucket: 'confess-272ce.appspot.com',
    measurementId: 'G-01M42XKYSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc5e5s5A1YxwOwJSRZnrKsht7zROLf4d0',
    appId: '1:500945831833:android:01e5792d9f49700e2f3508',
    messagingSenderId: '500945831833',
    projectId: 'confess-272ce',
    storageBucket: 'confess-272ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJqk0awE_oy9dxla47LEU2XlYH60r67pg',
    appId: '1:500945831833:ios:7834c095aa8be5962f3508',
    messagingSenderId: '500945831833',
    projectId: 'confess-272ce',
    storageBucket: 'confess-272ce.appspot.com',
    iosBundleId: 'com.promox.confess',
  );
}
