// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkLXixpR2W3B1zEo5xVjmgUq63NXezmA0',
    appId: '1:642988925358:web:9777befbe4f90a6c4e283f',
    messagingSenderId: '642988925358',
    projectId: 'confeife',
    authDomain: 'confeife.firebaseapp.com',
    storageBucket: 'confeife.appspot.com',
    measurementId: 'G-SN9ZCRNQCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwOrwsGfebwnlLDalz64VmwvESZ7V1hes',
    appId: '1:642988925358:android:4ef7da62f045286a4e283f',
    messagingSenderId: '642988925358',
    projectId: 'confeife',
    storageBucket: 'confeife.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6v7w-gAN2sQUxTeOOa_RVFrfaV-4uC0',
    appId: '1:642988925358:ios:ca9bedb0615a94a34e283f',
    messagingSenderId: '642988925358',
    projectId: 'confeife',
    storageBucket: 'confeife.appspot.com',
    androidClientId: '642988925358-ffk8oljk6l4sqokfk43o8p9prpkpprm0.apps.googleusercontent.com',
    iosClientId: '642988925358-4m8g3ek80ssl9c3sgc0ferur61s2r7d3.apps.googleusercontent.com',
    iosBundleId: 'com.promox.confess',
  );
}
